### ISSUE TITLE
Playback is broken

### ISSUE THREAD

**Issue by alsoGAMER** [kutzlect/io.github.thaunknown.miru#4] opened 2023-05-10 12:26 UTC
Playback stopped working entirely since a bunch of builds ago (2w at least), i'm trying to figure out why is that and i think the root cause is somewhere in the webtorrent logic.

Everything works fine till miru tries to load the reach webtorrent client (eg: http://localhost:40103/webtorrent/8b0e035787323666ee0d51a93a4cc3e4d79aceea/someFile.mkv)

Maybe flatpaks can't expose services on random ports?

**Comment by ecficies** [comment] 2023-05-10 14:05
Well, I did some testing and it seems to be working fine. Can you provide a video maybe?

**Comment by alsoGAMER** [comment] 2023-05-10 15:02
Sure, there you go https://files.catbox.moe/9ckhud.mkv.

**Comment by ecficies** [comment] 2023-05-10 15:52
Okay, I was able to reproduce it as well. Seems like it only affects episodes where there are very few seeders.

**Comment by kutzlect** [comment] 2023-05-10 16:10
Apparently it might be the AppImage's fault?
I ran Miru from the AUR (which uses the .deb) and the flatpak side-by-side with One Piece and both are unable to play the first episode. However, for some reason the one from the AUR jumps to the 892nd episode and the flatpak doesn't even though it can play the same episode.
Can you replicate this?

**Comment by alsoGAMER** [comment] 2023-05-10 20:56
Deb package (used for the AUR one) isn't affect by this though, maybe as you said earlier, there's something wrong with the appimage?

**Comment by ecficies** [comment] 2023-05-10 21:43
nah, I made a manifest with the deb package but it has the same issue (you can check it out for yourself on the deb branch)

**Comment by alsoGAMER** [comment] 2023-05-11 08:59
@kutzlect I'm not affected by this with the Deb build though...

**Comment by kutzlect** [comment] 2023-05-11 09:21
That's surprising... Anyways, if you're willing to make another video, I shall replace it.
------- Original Message -------
2023. május 11., csütörtök 10:59 keltezéssel, alsoGAMER ***@***.***> írta:

**Comment by ecficies** [comment] 2023-05-11 09:23
That's surprising... Anyways, if you're willing to make another video, I shall replace it.

**Comment by alsoGAMER** [comment] 2023-05-11 12:27
Ok it seems like i'm now having a similar issue with the DEB build too, though this time it seems like its continuing trying to fetch the video, unlike with the flatpak build (network traffic is still ongoing)

https://files.catbox.moe/l0x9e4.mkv

**Comment by ecficies** [comment] 2023-07-05 20:26
It probably has something to do with the site where the content is being streamed from. I can't really do anything about it, so I'll close this one.

**Closed as completed by ecficies** 2023-07-05 20:26 UTC
